server.port = 9999
game.duration = 120
users.file = /Users/chaulagain/Downloads/idea/DataClient
game.file = /Users/chaulagain/Downloads/idea/src/Server/game.json
stats.file = /Users/chaulagain/Downloads/idea/src/Server/playerstats.json
